### ISSUE TITLE
Pomona Farms Ag

### ISSUE THREAD

**Issue by JStaniforth** [SoaringUSA/turnpoints#21]
BB noticed this outlanding place WSW of Skydive SJ (formerly DB Cooper)
Lat/Lon/El/Dir/Len/Wid/Desc

N35°05.040'
W119°12.959'
460ft
0
4000ft
35ft
35' asphalt, 120' clear between fruit trees. BB spotted from air 2022

**Comment by rocketman768** [comment]
Fixed in 29c7fbe
