### ISSUE TITLE
Aro Pistachios Strip

### ISSUE THREAD

**Issue by JStaniforth** [SoaringUSA/turnpoints#22]
BB spotted this outlanding place ENE of Ducor over the weekend.
Lat/Lon/El/Dir/Len/Wid/Desc

N35°54.099'
W119°00.172'
621ft
150
2000ft
50ft
2000' x 50' paved. Trees 15' off W side, E side could be low crop. Tel 559-535-1500. BB spotted from air 2022.

**Comment by rocketman768** [comment]
Fixed in 29c7fbe
